// Code generated by "marker -method IsAggregation -output aggregation_marker_generated.go -type count,min,max,sum,product,avg"; DO NOT EDIT.

package function

func (*count) IsAggregation()   {}
func (*min) IsAggregation()     {}
func (*max) IsAggregation()     {}
func (*sum) IsAggregation()     {}
func (*product) IsAggregation() {}
func (*avg) IsAggregation()     {}
