package token

import (
	"encoding/json"
	"fmt"
)

type (
	// Token is a token generated by lexical analysis.
	Token interface {
		Type() int
		Value() string
	}

	token struct {
		t int
		v string
	}
)

func New(t int, v string) Token {
	return &token{
		t: t,
		v: v,
	}
}

func (s *token) Type() int      { return s.t }
func (s *token) Value() string  { return s.v }
func (s *token) String() string { return fmt.Sprintf("type %d value %s", s.t, s.v) }
func (s *token) MarshalJSON() ([]byte, error) {
	return json.Marshal(map[string]interface{}{
		"type":  s.t,
		"value": s.v,
	})
}
