// Code generated by "stringer -type ArithmeticOperatorType -output arithmetic_operator_type_stringer_generated.go"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ArtOpAdd-0]
	_ = x[ArtOpSubtract-1]
	_ = x[ArtOpMultiply-2]
	_ = x[ArtOpDivide-3]
}

const _ArithmeticOperatorType_name = "ArtOpAddArtOpSubtractArtOpMultiplyArtOpDivide"

var _ArithmeticOperatorType_index = [...]uint8{0, 8, 21, 34, 45}

func (i ArithmeticOperatorType) String() string {
	if i < 0 || i >= ArithmeticOperatorType(len(_ArithmeticOperatorType_index)-1) {
		return "ArithmeticOperatorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ArithmeticOperatorType_name[_ArithmeticOperatorType_index[i]:_ArithmeticOperatorType_index[i+1]]
}
