// Code generated by "stringer -type BitOperatorType -output bit_operator_type_stringer_generated.go"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BitOpAnd-0]
	_ = x[BitOpOr-1]
	_ = x[BitOpXor-2]
}

const _BitOperatorType_name = "BitOpAndBitOpOrBitOpXor"

var _BitOperatorType_index = [...]uint8{0, 8, 15, 23}

func (i BitOperatorType) String() string {
	if i < 0 || i >= BitOperatorType(len(_BitOperatorType_index)-1) {
		return "BitOperatorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BitOperatorType_name[_BitOperatorType_index[i]:_BitOperatorType_index[i+1]]
}
