// Code generated by "marker -method IsBitExpr -type BitExprBitOp,BitExprArtOp,BitExprSimpleExpr -output bit_expr_marker_generated.go"; DO NOT EDIT.

package ast

func (*BitExprBitOp) IsBitExpr()      {}
func (*BitExprArtOp) IsBitExpr()      {}
func (*BitExprSimpleExpr) IsBitExpr() {}
