// Code generated by "marker -method IsBoolPrimary -type BoolPrimaryComparison,BoolPrimaryPredicate -output bool_primary_marker_generated.go"; DO NOT EDIT.

package ast

func (*BoolPrimaryComparison) IsBoolPrimary() {}
func (*BoolPrimaryPredicate) IsBoolPrimary()  {}
