// Code generated by "stringer -type ComparisonType -output comparison_type_stringer_generated.go"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CmpEqual-0]
	_ = x[CmpNotEqual-1]
	_ = x[CmpGreaterThan-2]
	_ = x[CmpGreaterEqual-3]
	_ = x[CmpLessThan-4]
	_ = x[CmpLessEqual-5]
}

const _ComparisonType_name = "CmpEqualCmpNotEqualCmpGreaterThanCmpGreaterEqualCmpLessThanCmpLessEqual"

var _ComparisonType_index = [...]uint8{0, 8, 19, 33, 48, 59, 71}

func (i ComparisonType) String() string {
	if i < 0 || i >= ComparisonType(len(_ComparisonType_index)-1) {
		return "ComparisonType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ComparisonType_name[_ComparisonType_index[i]:_ComparisonType_index[i+1]]
}
