// Code generated by "marker -method IsNode,IsLit,IsExpr -type IntLit,FloatLit,StringLit -output lit_marker_generated.go"; DO NOT EDIT.

package ast

func (*IntLit) IsNode()    {}
func (*IntLit) IsLit()     {}
func (*IntLit) IsExpr()    {}
func (*FloatLit) IsNode()  {}
func (*FloatLit) IsLit()   {}
func (*FloatLit) IsExpr()  {}
func (*StringLit) IsNode() {}
func (*StringLit) IsLit()  {}
func (*StringLit) IsExpr() {}
