// Code generated by "marker -method IsPredicate -type PredicateIn,PredicateBetween,PredicateLike,PredicateBitExpr -output predicate_marker_generated.go"; DO NOT EDIT.

package ast

func (*PredicateIn) IsPredicate()      {}
func (*PredicateBetween) IsPredicate() {}
func (*PredicateLike) IsPredicate()    {}
func (*PredicateBitExpr) IsPredicate() {}
