// Code generated by "stringer -type PrefixOperatorType -output prefix_operator_stringer_generated.go"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PreOpPlus-0]
	_ = x[PreOpMinus-1]
	_ = x[PreOpBitNot-2]
	_ = x[PreOpNot-3]
}

const _PrefixOperatorType_name = "PreOpPlusPreOpMinusPreOpBitNotPreOpNot"

var _PrefixOperatorType_index = [...]uint8{0, 9, 19, 30, 38}

func (i PrefixOperatorType) String() string {
	if i < 0 || i >= PrefixOperatorType(len(_PrefixOperatorType_index)-1) {
		return "PrefixOperatorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PrefixOperatorType_name[_PrefixOperatorType_index[i]:_PrefixOperatorType_index[i+1]]
}
