// Code generated by "marker -method IsSection -type SelectSection,WhereSection,HavingSection,GroupBySection,OrderBySection,LimitSection -output section_marker_generated.go"; DO NOT EDIT.

package ast

func (*SelectSection) IsSection()  {}
func (*WhereSection) IsSection()   {}
func (*HavingSection) IsSection()  {}
func (*GroupBySection) IsSection() {}
func (*OrderBySection) IsSection() {}
func (*LimitSection) IsSection()   {}
