// Code generated by "marker -method IsNode -type SelectSection,SelectTerms,SelectTerm,SelectOption,SelectTarget,WhereSection,WhereCondition,GroupBySection,GroupByTerms,GroupByTerm,HavingSection,OrderBySection,OrderByTerms,OrderByTerm,OrderByTermOption,LimitSection -output section_node_marker_generated.go"; DO NOT EDIT.

package ast

func (*SelectSection) IsNode()     {}
func (*SelectTerms) IsNode()       {}
func (*SelectTerm) IsNode()        {}
func (*SelectOption) IsNode()      {}
func (*SelectTarget) IsNode()      {}
func (*WhereSection) IsNode()      {}
func (*WhereCondition) IsNode()    {}
func (*GroupBySection) IsNode()    {}
func (*GroupByTerms) IsNode()      {}
func (*GroupByTerm) IsNode()       {}
func (*HavingSection) IsNode()     {}
func (*OrderBySection) IsNode()    {}
func (*OrderByTerms) IsNode()      {}
func (*OrderByTerm) IsNode()       {}
func (*OrderByTermOption) IsNode() {}
func (*LimitSection) IsNode()      {}
