// Code generated by "marker -method IsSimpleExpr -type SimpleExprPrefixOp,SimpleExprLit,Ident,FunctionCall,SimpleExprExpr -output simple_expr_marker_generated.go"; DO NOT EDIT.

package ast

func (*SimpleExprPrefixOp) IsSimpleExpr() {}
func (*SimpleExprLit) IsSimpleExpr()      {}
func (*Ident) IsSimpleExpr()              {}
func (*FunctionCall) IsSimpleExpr()       {}
func (*SimpleExprExpr) IsSimpleExpr()     {}
