// Code generated by "stringer -type Type -output data_type_stringer_generated.go"; DO NOT EDIT.

package data

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeInt-0]
	_ = x[TypeFloat-1]
	_ = x[TypeString-2]
	_ = x[TypeBool-3]
}

const _Type_name = "TypeIntTypeFloatTypeStringTypeBool"

var _Type_index = [...]uint8{0, 7, 16, 26, 34}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
