// Code generated by "stringer -type Type -output cast_stringer_generated.go"; DO NOT EDIT.

package cast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeUndefined-0]
	_ = x[TypeInt-1]
	_ = x[TypeFloat-2]
	_ = x[TypeString-3]
	_ = x[TypeBool-4]
	_ = x[TypeTimestamp-5]
	_ = x[TypeTime-6]
	_ = x[TypeDuration-7]
}

const _Type_name = "TypeUndefinedTypeIntTypeFloatTypeStringTypeBoolTypeTimestampTypeTimeTypeDuration"

var _Type_index = [...]uint8{0, 13, 20, 29, 39, 47, 60, 68, 80}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
