// Code generated by "stringer -type Result -output compare_stringer_generated.go"; DO NOT EDIT.

package compare

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ResultUndefined-0]
	_ = x[ResultEqual-1]
	_ = x[ResultLessThan-2]
	_ = x[ResultGreaterThan-3]
	_ = x[ResultIn-4]
	_ = x[ResultNotIn-5]
	_ = x[ResultMatched-6]
	_ = x[ResultNotMatched-7]
}

const _Result_name = "ResultUndefinedResultEqualResultLessThanResultGreaterThanResultInResultNotInResultMatchedResultNotMatched"

var _Result_index = [...]uint8{0, 15, 26, 40, 57, 65, 76, 89, 105}

func (i Result) String() string {
	if i < 0 || i >= Result(len(_Result_index)-1) {
		return "Result(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Result_name[_Result_index[i]:_Result_index[i+1]]
}
